apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediamtx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediamtx
  template:
    metadata:
      labels:
        app: mediamtx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: mediamtx
          image: bluenviron/mediamtx:latest
          imagePullPolicy: IfNotPresent
          env:
            # Optional: force RTSP TCP if you don’t want UDP transport
            # - name: MTX_RTSPTRANSPORTS
            #   value: "tcp"

            # Optional: tell WebRTC which IP/DNS to advertise to peers
            # - name: MTX_WEBRTCADDITIONALHOSTS
            #   value: "192.168.100.8"
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: mediamtx-tcp
spec:
  type: LoadBalancer    # or NodePort
  selector: { app: mediamtx }
  ports:
    - { name: rtsp, port: 8554, targetPort: rtsp, protocol: TCP }
    - { name: rtmp, port: 1935, targetPort: rtmp, protocol: TCP }
    - { name: hls,  port: 8888, targetPort: hls,  protocol: TCP }
    - { name: webr, port: 8889, targetPort: webr, protocol: TCP }
    - { name: api,  port: 9997, targetPort: api,  protocol: TCP }

---

apiVersion: v1
kind: Service
metadata:
  name: mediamtx-udp
spec:
  type: LoadBalancer    # or NodePort
  selector: { app: mediamtx }
  ports:
    - { name: srt,  port: 8890, targetPort: srt,  protocol: UDP }
    - { name: wrtc, port: 8189, targetPort: wrtc, protocol: UDP }
