apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-metrics
  labels:
    app: flask-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-metrics
  template:
    metadata:
      labels:
        app: flask-metrics
    spec:
      containers:
      - name: flask-metrics
        image: fauzanghaza/flask-metrics:latest  # <-- build & push your image
        ports:
        - containerPort: 5000   # app
        - containerPort: 8000   # metrics
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-metrics
  labels:
    app: flask-metrics
spec:
  selector:
    app: flask-metrics
  ports:
  - name: http-app
    port: 5000
    targetPort: 5000
  - name: http-metrics
    port: 8000
    targetPort: 8000
