apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-metrics
  namespace: metrics    # same namespace as your kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: flask-metrics
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
