apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pg-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.34.4.196-10.34.4.197
    - 10.34.4.199-10.34.4.200

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv
  namespace: metallb-system
spec: {}
